#!/usr/bin/env bash

set -euo pipefail

# ============================================================
# Tradie Job Manager - Linux Environment Setup
# Works with infra/docker-compose.yml using:
# db:5432 mapped to localhost:5433
# redis:6379 mapped to localhost:6380
# minio:9000 mapped to localhost:9000
# ============================================================

PROJECT_ROOT="/home/inso/Documents/My_Portfolio/Tradie"
BACKEND_DIR="$PROJECT_ROOT/backend"
INFRA_DIR="$PROJECT_ROOT/infra"
ENV_FILE="$BACKEND_DIR/.env"
ENV_EXAMPLE_FILE="$BACKEND_DIR/.env.example"

POSTGRES_USER="tradie"
POSTGRES_PASSWORD="tradie_secret"
POSTGRES_DB="tradie"

HOST_POSTGRES_PORT="5433"
CONTAINER_POSTGRES_PORT="5432"

REDIS_PASSWORD="redis_secret"
HOST_REDIS_PORT="6380"
CONTAINER_REDIS_PORT="6379"

MINIO_ACCESS_KEY="tradie_minio"
MINIO_SECRET_KEY="tradie_minio_secret"
MINIO_PORT="9000"
MINIO_CONSOLE_PORT="9001"

API_PORT="8080"
APP_ENV="development"

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

JWT_SECRET="$(generate_secret)"

echo "Checking project folders..."

if [ ! -d "$BACKEND_DIR" ]; then
  echo "ERROR: Backend folder not found: $BACKEND_DIR"
  exit 1
fi

if [ ! -d "$INFRA_DIR" ]; then
  echo "ERROR: Infra folder not found: $INFRA_DIR"
  exit 1
fi

if [ ! -f "$INFRA_DIR/docker-compose.yml" ]; then
  echo "ERROR: docker-compose.yml not found: $INFRA_DIR/docker-compose.yml"
  exit 1
fi

echo "Checking Docker..."

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker is not installed or not available."
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: Docker Compose plugin is not working."
  exit 1
fi

echo "Creating backend .env..."

if [ -f "$ENV_FILE" ]; then
  BACKUP_FILE="$ENV_FILE.backup.$(date +%Y%m%d-%H%M%S)"
  cp "$ENV_FILE" "$BACKUP_FILE"
  echo "Old .env backed up to: $BACKUP_FILE"
fi

cat > "$ENV_FILE" <<EOF
# ============================================================
# Tradie Job Manager Backend Environment
# Generated by setup-env.sh
# For local Linux backend development
# ============================================================

APP_ENV=$APP_ENV
PORT=$API_PORT

# Local Linux host values
# Use these when running: go run ./cmd/api/main.go
DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:$HOST_POSTGRES_PORT/$POSTGRES_DB?sslmode=disable
REDIS_URL=redis://:$REDIS_PASSWORD@localhost:$HOST_REDIS_PORT/0

JWT_SECRET=$JWT_SECRET

# S3 / MinIO values for local backend
S3_ENDPOINT=http://localhost:$MINIO_PORT
S3_ACCESS_KEY=$MINIO_ACCESS_KEY
S3_SECRET_KEY=$MINIO_SECRET_KEY
S3_BUCKET=tradie
S3_REGION=us-east-1
S3_USE_SSL=false

# Extra MinIO compatibility variables
MINIO_ENDPOINT=localhost:$MINIO_PORT
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY
MINIO_USE_SSL=false
EOF

chmod 600 "$ENV_FILE"

cat > "$ENV_EXAMPLE_FILE" <<EOF
APP_ENV=development
PORT=8080

DATABASE_URL=postgres://USER:PASSWORD@localhost:5433/DATABASE?sslmode=disable
REDIS_URL=redis://:PASSWORD@localhost:6380/0

JWT_SECRET=change-this-secret

S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY=change-this
S3_SECRET_KEY=change-this
S3_BUCKET=tradie
S3_REGION=us-east-1
S3_USE_SSL=false

MINIO_ENDPOINT=localhost:9000
MINIO_ACCESS_KEY=change-this
MINIO_SECRET_KEY=change-this
MINIO_USE_SSL=false
EOF

echo "Starting Docker services..."

cd "$INFRA_DIR"
docker compose up -d db redis minio

echo "Waiting for PostgreSQL to become ready..."

for i in {1..20}; do
  if docker compose exec -T db pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
    echo "PostgreSQL is ready."
    break
  fi

  if [ "$i" -eq 20 ]; then
    echo "ERROR: PostgreSQL did not become ready."
    docker compose logs db
    exit 1
  fi

  sleep 2
done

echo "Checking database exists..."

docker compose exec -T db psql \
  -U "$POSTGRES_USER" \
  -d "$POSTGRES_DB" \
  -c "SELECT current_database(), current_user, NOW();"

echo "Checking Redis..."

docker compose exec -T redis redis-cli -a "$REDIS_PASSWORD" ping || true

echo "Checking Docker containers..."

docker compose ps

HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"

echo
echo "============================================================"
echo "Tradie setup completed successfully"
echo "============================================================"
echo "Backend .env:"
echo "$ENV_FILE"
echo
echo "Local Linux DATABASE_URL:"
echo "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:$HOST_POSTGRES_PORT/$POSTGRES_DB?sslmode=disable"
echo
echo "Docker internal DATABASE_URL:"
echo "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$CONTAINER_POSTGRES_PORT/$POSTGRES_DB?sslmode=disable"
echo
echo "Local Linux REDIS_URL:"
echo "redis://:$REDIS_PASSWORD@localhost:$HOST_REDIS_PORT/0"
echo
echo "Docker internal REDIS_URL:"
echo "redis://:$REDIS_PASSWORD@redis:$CONTAINER_REDIS_PORT/0"
echo
echo "MinIO API:"
echo "http://localhost:$MINIO_PORT"
echo
echo "MinIO Console:"
echo "http://localhost:$MINIO_CONSOLE_PORT"
echo
echo "Backend API:"
echo "http://localhost:$API_PORT"
echo
echo "Flutter API URLs:"
echo "Android emulator: http://10.0.2.2:$API_PORT"
echo "Linux desktop/web: http://localhost:$API_PORT"

if [ -n "$HOST_IP" ]; then
  echo "Physical phone on same WiFi: http://$HOST_IP:$API_PORT"
fi

echo
echo "Next command for local backend:"
echo "cd $BACKEND_DIR"
echo "go run ./cmd/api/main.go"
echo "============================================================"
