DROP TABLE IF EXISTS superannuation CASCADE;
DROP TABLE IF EXISTS payslips CASCADE;
DROP TABLE IF EXISTS pay_runs CASCADE;
DROP TABLE IF EXISTS leave_requests CASCADE;
DROP TABLE IF EXISTS timesheets CASCADE;
DROP TABLE IF EXISTS worker_check_ins CASCADE;
DROP TABLE IF EXISTS worker_locations CASCADE;
DROP TABLE IF EXISTS worker_availability CASCADE;
